version: '3'
services:
  www:
    image: 'ciebit/deno'
    ports:
      - '8000:80'
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: deno run --unstable --allow-net --allow-read server.ts
  app:
    image: 'ciebit/deno'
    ports:
      - '8000:80'
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: deno run main.ts
  deno:
    image: 'ciebit/deno'
    volumes:
      - ./app:/app
    working_dir: /app
  tests-unit:
    image: 'ciebit/deno'
    volumes:
      - .:/project
    working_dir: /project
    entrypoint: deno test tests/app/Entities
  tests-integration:
    image: 'ciebit/deno'
    volumes:
      - .:/project
    working_dir: /project
    entrypoint: deno test --allow-read --allow-write --unstable tests/app/Repositories
